from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QApplication, QMainWindow, QPushButton
import pickle

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1108, 588)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Button_1 = QtWidgets.QPushButton(self.centralwidget)
        self.Button_1.setGeometry(QtCore.QRect(10, 440, 121, 41))
        self.Button_1.setObjectName("Button_1")
        self.Button_2 = QtWidgets.QPushButton(self.centralwidget)
        self.Button_2.setGeometry(QtCore.QRect(10, 490, 121, 41))
        self.Button_2.setObjectName("Button_2")
        self.Button_3 = QtWidgets.QPushButton(self.centralwidget)
        self.Button_3.setGeometry(QtCore.QRect(140, 440, 121, 41))
        self.Button_3.setText("")
        self.Button_3.setObjectName("Button_3")
        self.Button_4 = QtWidgets.QPushButton(self.centralwidget)
        self.Button_4.setGeometry(QtCore.QRect(140, 490, 121, 41))
        self.Button_4.setText("")
        self.Button_4.setObjectName("Button_4")
        self.Button_5 = QtWidgets.QPushButton(self.centralwidget)
        self.Button_5.setGeometry(QtCore.QRect(270, 440, 121, 41))
        self.Button_5.setText("")
        self.Button_5.setObjectName("Button_5")
        self.Button_6 = QtWidgets.QPushButton(self.centralwidget)
        self.Button_6.setGeometry(QtCore.QRect(270, 490, 121, 41))
        self.Button_6.setText("")
        self.Button_6.setObjectName("Button_6")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(0, 419, 661, 21))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.Button_7 = QtWidgets.QPushButton(self.centralwidget)
        self.Button_7.setGeometry(QtCore.QRect(400, 440, 121, 41))
        self.Button_7.setText("")
        self.Button_7.setObjectName("Button_7")
        self.Button_8 = QtWidgets.QPushButton(self.centralwidget)
        self.Button_8.setGeometry(QtCore.QRect(400, 490, 121, 41))
        self.Button_8.setText("")
        self.Button_8.setObjectName("Button_8")
        self.Abilities = QtWidgets.QLabel(self.centralwidget)
        self.Abilities.setGeometry(QtCore.QRect(890, 160, 211, 20))
        self.Abilities.setObjectName("Abilities")
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_2.setGeometry(QtCore.QRect(890, 20, 211, 141))
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.Stats = QtWidgets.QLabel(self.centralwidget)
        self.Stats.setGeometry(QtCore.QRect(890, 0, 211, 20))
        self.Stats.setObjectName("Stats")
        self.minimap = QtWidgets.QLabel(self.centralwidget)
        self.minimap.setGeometry(QtCore.QRect(0, 0, 200, 200))
        self.minimap.setText("")
        self.minimap.setPixmap(QtGui.QPixmap("cropped map.png"))
        self.minimap.setScaledContents(True)
        self.minimap.setObjectName("minimap")
        self.Button_9 = QtWidgets.QPushButton(self.centralwidget)
        self.Button_9.setGeometry(QtCore.QRect(530, 440, 121, 41))
        self.Button_9.setText("")
        self.Button_9.setObjectName("Button_9")
        self.Button_10 = QtWidgets.QPushButton(self.centralwidget)
        self.Button_10.setGeometry(QtCore.QRect(530, 490, 121, 41))
        self.Button_10.setText("")
        self.Button_10.setObjectName("Button_10")
        self.Inventory = QtWidgets.QLabel(self.centralwidget)
        self.Inventory.setGeometry(QtCore.QRect(660, 0, 141, 20))
        self.Inventory.setObjectName("Inventory")
        self.leftarw_3 = QtWidgets.QPushButton(self.centralwidget)
        self.leftarw_3.setGeometry(QtCore.QRect(90, 340, 28, 28))
        self.leftarw_3.setObjectName("leftarw_3")
        self.leftarw_5 = QtWidgets.QPushButton(self.centralwidget)
        self.leftarw_5.setGeometry(QtCore.QRect(30, 340, 28, 28))
        self.leftarw_5.setObjectName("leftarw_5")
        self.leftarw_6 = QtWidgets.QPushButton(self.centralwidget)
        self.leftarw_6.setGeometry(QtCore.QRect(60, 340, 28, 28))
        self.leftarw_6.setObjectName("leftarw_6")
        self.leftarw_7 = QtWidgets.QPushButton(self.centralwidget)
        self.leftarw_7.setGeometry(QtCore.QRect(60, 310, 28, 28))
        self.leftarw_7.setObjectName("leftarw_7")
        self.leftarw_8 = QtWidgets.QPushButton(self.centralwidget)
        self.leftarw_8.setGeometry(QtCore.QRect(90, 310, 28, 28))
        self.leftarw_8.setObjectName("leftarw_8")
        self.leftarw_9 = QtWidgets.QPushButton(self.centralwidget)
        self.leftarw_9.setGeometry(QtCore.QRect(30, 310, 28, 28))
        self.leftarw_9.setObjectName("leftarw_9")
        self.sell_1 = QtWidgets.QPushButton(self.centralwidget)
        self.sell_1.setGeometry(QtCore.QRect(840, 500, 41, 28))
        self.sell_1.setObjectName("sell_1")
        self.select_1 = QtWidgets.QPushButton(self.centralwidget)
        self.select_1.setGeometry(QtCore.QRect(1060, 500, 41, 28))
        self.select_1.setObjectName("select_1")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(0, 210, 93, 28))
        self.pushButton.setObjectName("pushButton")
        self.textBrowser_4 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_4.setGeometry(QtCore.QRect(210, 0, 441, 421))
        self.textBrowser_4.setObjectName("textBrowser_4")
        self.equip_1 = QtWidgets.QPushButton(self.centralwidget)
        self.equip_1.setGeometry(QtCore.QRect(800, 500, 41, 28))
        self.equip_1.setObjectName("equip_1")
        self.listWidget = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget.setGeometry(QtCore.QRect(660, 20, 221, 481))
        self.listWidget.setObjectName("listWidget")
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        self.listWidget_2 = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget_2.setGeometry(QtCore.QRect(890, 180, 211, 321))
        self.listWidget_2.setObjectName("listWidget_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1108, 26))
        self.menubar.setObjectName("menubar")
        self.menufile = QtWidgets.QMenu(self.menubar)
        self.menufile.setObjectName("menufile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionsave = QtWidgets.QAction(MainWindow)
        self.actionsave.setObjectName("actionsave")
        self.actionload = QtWidgets.QAction(MainWindow)
        self.actionload.setObjectName("actionload")
        self.menufile.addAction(self.actionsave)
        self.menufile.addAction(self.actionload)
        self.menubar.addAction(self.menufile.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Abilities.setText(_translate("MainWindow", "Abilities"))
        self.Stats.setText(_translate("MainWindow", "Stats"))
        self.Inventory.setText(_translate("MainWindow", "Inventory"))
        self.leftarw_3.setText(_translate("MainWindow", "SE"))
        self.leftarw_5.setText(_translate("MainWindow", "SW"))
        self.leftarw_6.setText(_translate("MainWindow", "S"))
        self.leftarw_7.setText(_translate("MainWindow", "N"))
        self.leftarw_8.setText(_translate("MainWindow", "NE"))
        self.leftarw_9.setText(_translate("MainWindow", "NW"))
        self.sell_1.setText(_translate("MainWindow", "Sell"))
        self.select_1.setText(_translate("MainWindow", "Select"))
        self.pushButton.setText(_translate("MainWindow", "Map"))
        self.equip_1.setText(_translate("MainWindow", "Equip"))
        __sortingEnabled = self.listWidget.isSortingEnabled()
        self.listWidget.setSortingEnabled(False)
        item = self.listWidget.item(0)
        item.setText(_translate("MainWindow", "car"))
        item = self.listWidget.item(1)
        item.setText(_translate("MainWindow", "2"))
        self.listWidget.setSortingEnabled(__sortingEnabled)
        self.menufile.setTitle(_translate("MainWindow", "file"))
        self.actionsave.setText(_translate("MainWindow", "save"))
        self.actionload.setText(_translate("MainWindow", "load"))
